name: Publish Vite Plugin

on:
  workflow_call:
    inputs:
      version:
        description: 'The version being published'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all workspaces
        run: npm run build --workspaces --if-present

      - name: Publish Vite Plugin
        if: "!contains(inputs.version, '-dev')"
        # We target the specific workspace to publish
        run: npm publish --workspace plugins/vite-plugin-template --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}